project:
  type: default
  render:
    - "syllabus/*.qmd"
    - "setup/*.qmd"
    - "sessions/**/*.qmd"
    - "assignments/**/*.qmd"
    - "!instructor/"
    - "!assignments/group-project/report.qmd"
  output-dir: _site

jupyter: python3
execute:
  freeze: auto
  warning: false
  error: false

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    embed-resources: true
