"""
Convert the session quizzes (sessions/0X-*/quiz.md) to GIFT format for Moodle or Canvas.

Source format: numbered questions, options a) to d), a line "Answer: x" and a
line "Rationale: ..." (see assignments/quizzes/README.md).

    python assignments/quizzes/convert_quiz.py                 # all sessions -> assignments/quizzes/session0X.gift
    python assignments/quizzes/convert_quiz.py --input FILE --output FILE
    python assignments/quizzes/convert_quiz.py --check         # validate only
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = Path(__file__).resolve().parent

RE_QUESTION = re.compile(r"^\s*(?:#+\s*)?(?:\*\*)?(\d{1,2})[.)](?:\*\*)?\s+(.*)$")
RE_OPTION = re.compile(r"^\s*(?:[-*]\s+)?(?:\*\*)?\(?([a-dA-D])[.)](?:\*\*)?\s+(.*)$")
RE_ANSWER = re.compile(r"^\s*(?:[-*]\s+)?(?:\*\*)?Answer(?:\*\*)?\s*:?(?:\*\*)?\s*:?\s*\(?([a-dA-D])\)?\b", re.I)
RE_RATIONALE = re.compile(r"^\s*(?:[-*]\s+)?(?:\*\*)?Rationale(?:\*\*)?\s*:?(?:\*\*)?\s*:?\s*(.*)$", re.I)


@dataclass
class Question:
    number: int
    text: str
    options: dict[str, str] = field(default_factory=dict)
    answer: str | None = None
    rationale: str = ""


def parse_quiz(text: str) -> list[Question]:
    questions: list[Question] = []
    current: Question | None = None
    last_option: str | None = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if current is not None and (m := RE_ANSWER.match(line)):
            current.answer = m.group(1).lower()
            last_option = None
            continue
        if current is not None and (m := RE_RATIONALE.match(line)):
            current.rationale = m.group(1).strip()
            last_option = None
            continue
        if current is not None and (m := RE_OPTION.match(line)) and current.answer is None:
            letter = m.group(1).lower()
            current.options[letter] = m.group(2).strip()
            last_option = letter
            continue
        if m := RE_QUESTION.match(line):
            current = Question(number=int(m.group(1)), text=m.group(2).strip())
            questions.append(current)
            last_option = None
            continue
        if current is None or not line.strip():
            last_option = None if not line.strip() else last_option
            continue
        # continuation line
        if last_option is not None:
            current.options[last_option] += " " + line.strip()
        elif not current.options and current.answer is None:
            current.text += " " + line.strip()
        elif current.answer is not None and current.rationale:
            current.rationale += " " + line.strip()
    return questions


def validate(questions: list[Question], source: str) -> list[str]:
    problems = []
    if not questions:
        problems.append(f"{source}: no questions found")
    for q in questions:
        if len(q.options) != 4 or sorted(q.options) != ["a", "b", "c", "d"]:
            problems.append(f"{source} Q{q.number}: expected options a) to d), found {sorted(q.options)}")
        if q.answer is None:
            problems.append(f"{source} Q{q.number}: no 'Answer:' line")
        elif q.answer not in q.options:
            problems.append(f"{source} Q{q.number}: answer '{q.answer}' is not one of the options")
        if not q.rationale:
            problems.append(f"{source} Q{q.number}: no 'Rationale:' line")
        if not q.text:
            problems.append(f"{source} Q{q.number}: empty question text")
    return problems


def gift_escape(s: str) -> str:
    for ch in ("\\", "~", "=", "#", "{", "}", ":"):
        s = s.replace(ch, "\\" + ch)
    return s


def to_gift(questions: list[Question], prefix: str, title: str) -> str:
    out = [f"// {title}", f"// Generated by assignments/quizzes/convert_quiz.py; one correct answer per question.", ""]
    out.append(f"$CATEGORY: $course$/{gift_escape(title)}")
    out.append("")
    for q in questions:
        out.append(f"// question {q.number}")
        out.append(f"::{prefix} Q{q.number:02d}::{gift_escape(q.text)} {{")
        for letter in ("a", "b", "c", "d"):
            mark = "=" if letter == q.answer else "~"
            out.append(f"\t{mark}{gift_escape(q.options[letter])}")
        if q.rationale:
            out.append(f"\t####{gift_escape(q.rationale)}")
        out.append("}")
        out.append("")
    return "\n".join(out)


def quiz_title(text: str, fallback: str) -> str:
    for line in text.splitlines():
        if line.startswith("#"):
            return line.lstrip("#").strip()
    return fallback


def convert_file(src: Path, dst: Path | None, prefix: str, check_only: bool) -> bool:
    text = src.read_text(encoding="utf-8")
    questions = parse_quiz(text)
    problems = validate(questions, str(src))
    if problems:
        print("\n".join(problems), file=sys.stderr)
        return False
    title = quiz_title(text, src.parent.name)
    if check_only:
        print(f"{src}: {len(questions)} questions OK")
        return True
    assert dst is not None
    dst.write_text(to_gift(questions, prefix, title), encoding="utf-8")
    print(f"{src} -> {dst} ({len(questions)} questions)")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--input", help="a single quiz.md to convert")
    ap.add_argument("--output", help="output .gift path (with --input)")
    ap.add_argument("--check", action="store_true", help="validate only, write nothing")
    args = ap.parse_args()

    ok = True
    if args.input:
        src = Path(args.input)
        m = re.search(r"(\d{2})", src.parent.name)
        prefix = f"S{m.group(1)}" if m else src.stem.upper()
        dst = Path(args.output) if args.output else OUT_DIR / f"{src.stem}.gift"
        ok = convert_file(src, dst, prefix, args.check)
    else:
        sources = sorted((ROOT / "sessions").glob("0*/quiz.md"))
        if not sources:
            print("No sessions/0X-*/quiz.md files found yet.", file=sys.stderr)
            return 1
        for src in sources:
            num = src.parent.name[:2]
            dst = OUT_DIR / f"session{num}.gift"
            ok = convert_file(src, dst, f"S{num}", args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
